In [ ]:
import numpy as np

# Scalar Arithmetic -> One input is scalar, like a number to be added.
# Under the hood this is also Vector Arithmetic as 1 is converted to [1, 1, 1] and added vectorially in the array, ElementWise. But here one Input is Scalar, so can be thought as Scalar Arithmetic

array = np.array([1, 2, 3])
print (array + 1)
print (array - 2)
print(array * 3)
print (array/ 4)
print (array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [17]:
# Vector Arithmetic -> Element wise operation -> Input is a Single NxN matrix -> A vector
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))

[1.         1.41421356 1.73205081]
[1 2 3]
[1 2 3]
[1 2 3]


In [20]:
radii = np.array([1, 2, 3])
areas = radii ** 2 * np.pi 
print(areas)

[ 3.14159265 12.56637061 28.27433388]


In [23]:
# Element wise operations on 2 or more arrays -> More 'Vector Like' where inputs are NxN matrices
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [24]:
# Creating Boolean Arrays using Conditionals
scores = np.array([60, 62, 90, 100, 45, 32, 100])

# Students who passed
print(scores >= 60)
# Students who failed
print(scores < 60)
# Students with Full marks
print(scores == 100)


[ True  True  True  True False False  True]
[False False False False  True  True False]
[False False False  True False False  True]


In [27]:
# Assigning values to Truthy values in filtered array
scores[scores < 60] = 0
print(scores)

[ 60  62  90 100   0   0 100]
