In [1]:
# Filtering is the process of Selecting elements from an array which satisfy a particular condition

import numpy as np

# On 1D Arrays
oneDmarks = np.array([10, 20, 30, 40, 50, 60, 70])
# FLATTENS the original array to a single row in all the cases
# Original shape not preserved
filteredMarks = oneDmarks[oneDmarks >= 45]
print(filteredMarks) # A 1d array -> FLATTENS the original array to a single row

[50 60 70]


In [2]:
twoDmarks = np.array([[10, 20, 30, 40, 50, 60, 70],
                      [45, 89, 90, 100, 21, 34, 56]])
# FLATTENS the original array to a single row in all the cases
# Original shape not preserved
filteredMarks2 = twoDmarks[twoDmarks >= 45]
filteredMarks3 = twoDmarks[(twoDmarks >= 45) & (twoDmarks < 90)]
evenMarks = twoDmarks[twoDmarks % 2 == 0]
print(filteredMarks2) # A 1D array of elements >= 45
print(filteredMarks3) # A 1D array of elements >= 45 and < 90
print(evenMarks) # A 1D array of Even marks

[ 50  60  70  45  89  90 100  56]
[50 60 70 45 89 56]
[ 10  20  30  40  50  60  70  90 100  34  56]


In [6]:
# Preserving Original Shape of the Array using WHERE clause and replacing those values with Fill Values of 0, -1 or np.nan to preserve Rectangularity

# But the where clause is Slower than Boolean indexing. Unless we need to preserve the original shape, we don't tend to use it

filteredMarksOriginalShape = np.where(twoDmarks >= 45, twoDmarks, np.nan)
print(filteredMarksOriginalShape)

[[ nan  nan  nan  nan  50.  60.  70.]
 [ 45.  89.  90. 100.  nan  nan  56.]]
