In [ ]:
import numpy as np, random 

salary = np.array([random.randint(1, 101) for num in range(10)])

# Cumulative Sum and Cumulative Product operations
cum_sum_salaries = np.cumsum(salary)
cum_prod_salaries = np.cumprod(salary)

print(salary)
print(cum_sum_salaries)
print(cum_prod_salaries)


[43 47 79 24 16 72  5 11 43 35]
[ 43  90 169 193 209 281 286 297 340 375]
[             43            2021          159659         3831816
        61309056      4414252032     22071260160    242783861760
  10439706055680 365389711948800]


In [ ]:
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg 

arr_random_generator = gen(pcg(seed = 42)) # We tell NumPy to create a Random generator object which will generate random numbers using PCG algorithm
random_array = arr_random_generator.normal(size=(5, 5)) # Random numbers from -INFINITY to INFINITY excluded, following the Bell Curve, so mean will be around 0 always
print(random_array)


[[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
 [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
 [ 0.87939797  0.77779194  0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826   0.8784503  -0.04992591]
 [-0.18486236 -0.68092954  1.22254134 -0.15452948 -0.42832782]]


In [67]:
# Random numbers between 0 and 1 excluded, totally Random, not following any Curve
arr_random_generator = gen(pcg(seed = 10))
random_nums = arr_random_generator.random(size = (3, 3))
print(random_nums)

[[0.95600171 0.20768181 0.82844489]
 [0.14928212 0.51280462 0.1359196 ]
 [0.68903648 0.84174772 0.425509  ]]


In [68]:
# Random Integers between a LOW and HIGH range, HIGH excluded
arr_random_generator = gen(pcg(seed = 41))
randomInts = arr_random_generator.integers(low = 1, high = 101, size = (3, 3))
print(randomInts)

[[67 96 83]
 [77 71 13]
 [26 83 34]]


In [71]:
# Random Floating Point Numbers using .uniform(), for Uniform Distribution

arr_random_generator = gen(pcg(seed = 90))
random_floats = arr_random_generator.uniform(low = 1, high = 21, size = (2, 3))
print(random_floats)

[[ 8.4466556  14.63794215 11.37053436]
 [ 9.36700432 14.92623945  3.50781034]]


In [74]:
arr_random_generator = gen(pcg(seed = 100))
arr = np.array([1, 2, 3, 4, 5])
arr_random_generator.shuffle(arr)
print(arr)

[2 3 5 4 1]


In [ ]:
arr_random_generator = gen(pcg())
my_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Choose a Random Row with resppect to columns from an array. As wrt columns, so axis = 0
random_row_chosen = arr_random_generator.choice(my_arr, axis = 0)
print(random_row_chosen)
# Choose random number from that row
random_num_chosen = arr_random_generator.choice(random_row_chosen)
print(random_num_chosen)


# Choose a Random Column wrt rows. As wrt rows, axis = 1
random_col_chosen = arr_random_generator.choice(my_arr, axis = 1);
print(random_col_chosen)
# Choose a Random number from that column
random_num_chosen = arr_random_generator.choice(random_col_chosen)
print(random_num_chosen)


# Choose random element from 1D array and put it in a 2D array
print(arr_random_generator.choice(np.array(["apple", "orange", "banana", "pineapple", "mango"]), size = (3, 3)))

[4 5 6]
4
[2 5 8]
2
[['pineapple' 'mango' 'pineapple']
 ['mango' 'orange' 'mango']
 ['orange' 'orange' 'mango']]
