In [1]:
# Normal Python Array Slicing -> Row Selection
# SYNTAX: array[ startIndex : endIndex : step ], endIndex is Exclusive
import numpy as np

arr = np.array([
       [1, 2, 3], 
       [4, 5, 6], 
       [7, 8, 9]])

print(arr[0:3], end = "\n\n")
print(arr[0:], end = "\n\n")
print(arr[-1], end = "\n\n")
print(arr[0:3:2], end = "\n\n")
print(arr[::-1], end = "\n\n") # Reverse Array

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]

[[1 2 3]
 [7 8 9]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]



In [2]:
# Column Selection with all Rows selected -> Single Columns
print(arr[:, 1], end = "\n\n") # Select all rows, then select 2nd column (index = 1)
print(arr[:, -1]) # Select 1st column from ending

[2 5 8]

[3 6 9]


In [3]:
# Column Selection with all Rows selected -> Select Range of Columns, using Steps
print(arr[:, 0:3], end = "\n\n")
print(arr[:, 0:2], end = "\n\n")
print(arr[:, 0:3:2], end = "\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]]

[[1 3]
 [4 6]
 [7 9]]



In [4]:
# Column selection with Specific Rows selected
print(arr[0:2, 1], end="\n\n")
print(arr[0:3, 0:3:2], end="\n\n")

[2 5]

[[1 3]
 [4 6]
 [7 9]]



In [ ]:
# Indexing after slicing
x = arr[0:3, 0:3:2][0][1] # 1st element of 0th element of the sliced arr -> 3
print(x)
print(type(x))
x = int(x) # Convert (numpy.int64) to (Python Integer)
print(type(x))

3
<class 'numpy.int64'>
<class 'int'>
